### ISSUE TITLE
Formas de Pagamento

### ISSUE THREAD

**Issue by mpaiva** [mpaiva/leal-pub#16]
Check Payment
 PayPal PayPal
 Credit Card (Inspire Commerce) 
 Google Wallet Google Wallet

**Comment by emanweb** [comment]
Google wallet was discontinued by Google.

**Comment by mpaiva** [comment]
Eu copiei e colei as opções da Edicei, entao seria bom remover lá tambem,
não acha?

**Comment by emanweb** [comment]
O site dá Edicei esta completamente desatualizado. Tem uma versão no dev.ediceiofamerica.com onde estou testando as ultimas versões do Woo, WP e plugins. Devo terminar até o final do mês e colocar no ar.
